### ISSUE TITLE
<<type>> macro doest when callen Config.passages.onProcess

### ISSUE THREAD

**Issue by Fideruchan** [cyrusfirheir/cycy-wrote-custom-macros#13]
```
Config.passages.onProcess = function (p) { 
    if (p.tags.includes('typed') && settings.type_dissabled) {
		var $speed_setting = '<<type ' + settings.typed_speed + 'ms>>'
        return $speed_setting + p.text + '<</type>>'; /* adjust this however you see fit */
    } else {
        return p.text;
    }
}
```
Returns empty output. Type macro is not triggered. Thanks!

**Comment by cyrusfirheir** [comment]
I am not the author for the `<<type>>` macro. `<<type>>` is a SugarCube built-in, and you can take this up with [SugarCube 2](https://github.com/tmedwards/sugarcube-2/).

**Comment by Fideruchan** [comment]
Sorry, maybe i put it on the wrong place. I will ask my problem in the discussion if anyone can help me with this. Thanks!
