### ISSUE TITLE
Flash on listbox with liveupdate

### ISSUE THREAD

**Issue by SjoerdHekking** [cyrusfirheir/cycy-wrote-custom-macros#8]
![test5](https://user-images.githubusercontent.com/19780018/147511176-c04c274f-db19-4cc8-b92d-3afd956dbde1.gif)

```
<<liveblock>>
	<<run setup.GameTime($City.long, $City.lat)>>
	<p id="city-button" class="passage-text default-button city-continue-button hidden">
	<<link "Start the game!">>
		/* stuff */
	<</link>>
	</p>
<</liveblock>>

<<script>>
	$(document).on("click", "#listbox-city", function () {
		$(document).trigger(":liveupdate");
		$("#city-button").removeClass("hidden");
	});
<</script>>
```
Expected behavior, no flashing.

Removing the `$(document).trigger(":liveupdate");` fixes everything.

See GIF for the problem. See code for what I've done.

Possible fix, unsure.

Yours sincerely,
Sjoerd Hekking Redsea

**Comment by cyrusfirheir** [comment]
Change the event to `change` instead of `click`.
