### ISSUE TITLE
Help please with liveupdate and listboxes

### ISSUE THREAD

**Issue by WinterMUD** [cyrusfirheir/cycy-wrote-custom-macros#9]
I have two listboxes on the passage and I want to change content of the second listbox when option of the first listbox chosen. How to do this with your macros without page reloading?

**Comment by cyrusfirheir** [comment]
You could use the event that is used in the process. As an example:

```html
<span id="controller-list">
  <<listbox "$one">>
    <!-- ... -->>
  <</listbox>>
</span>

<<liveblock>>
  <!-- stuff for second listbox -->
<</liveblock>>

<<done>>
  <<run $("#controller-list").on("change", function() {
    $(document).trigger(":liveupdate");
  })>>
<</done>>
```

**Comment by cyrusfirheir** [comment]
Future note: I have just set up community discussion for this project, and you can put up questions like these on there from now onwards.

**Comment by WinterMUD** [comment]
Thanks! It works now. But it need to change 'change' on 'click'. Sorry for question in unaprepriate place, I'm not good understand Github system.

**Comment by cyrusfirheir** [comment]
It's no problem. I had not set up the discussions page before this, so is all good.
